/* tslint:disable */
/* eslint-disable */
/**
 * Tech Web - OpenAPI 3.0
 * Prova
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from './models/runtime'
import type { Problem } from './models/index'
import { ProblemFromJSON, ProblemToJSON } from './models/index'

/**
 *
 */
export class PublicApi extends runtime.BaseAPI {
  /**
   * Ritorna lo stato dell\'applicazione in formato problem+json
   * Ritorna lo stato dell\'applicazione
   */
  async statusGetRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Problem>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/status`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => ProblemFromJSON(jsonValue))
  }

  /**
   * Ritorna lo stato dell\'applicazione in formato problem+json
   * Ritorna lo stato dell\'applicazione
   */
  async statusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Problem> {
    const response = await this.statusGetRaw(initOverrides)
    return await response.value()
  }
}
