/* tslint:disable */
/* eslint-disable */
/**
 * Tech Web - OpenAPI 3.0
 * Prova
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from './models/runtime'
import type { Problem, QuestionDto } from './models/index'
import {
  ProblemFromJSON,
  ProblemToJSON,
  QuestionDtoFromJSON,
  QuestionDtoToJSON
} from './models/index'

export interface GetQuestionsByQuizRequest {
  idQuiz: string
}

/**
 *
 */
export class QuestionsApi extends runtime.BaseAPI {
  /**
   * Restituisce tutte le domande (aperte e/o chiuse) di un quiz
   */
  async getQuestionsByQuizRaw(
    requestParameters: GetQuestionsByQuizRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<QuestionDto>>> {
    if (requestParameters['idQuiz'] == null) {
      throw new runtime.RequiredError(
        'idQuiz',
        'Required parameter "idQuiz" was null or undefined when calling getQuestionsByQuiz().'
      )
    }

    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/questions/{idQuiz}`.replace(
          `{${'idQuiz'}}`,
          encodeURIComponent(String(requestParameters['idQuiz']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters
      },
      initOverrides
    )

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(QuestionDtoFromJSON))
  }

  /**
   * Restituisce tutte le domande (aperte e/o chiuse) di un quiz
   */
  async getQuestionsByQuiz(
    requestParameters: GetQuestionsByQuizRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<QuestionDto>> {
    const response = await this.getQuestionsByQuizRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
