/* tslint:disable */
/* eslint-disable */
/**
 * Tech Web - OpenAPI 3.0
 * Prova
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime'
/**
 *
 * @export
 * @interface AnswerDto
 */
export interface AnswerDto {
  /**
   *
   * @type {string}
   * @memberof AnswerDto
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof AnswerDto
   */
  text: string
  /**
   *
   * @type {boolean}
   * @memberof AnswerDto
   */
  isCorrect: boolean
  /**
   *
   * @type {string}
   * @memberof AnswerDto
   */
  idQuestion?: string
  /**
   *
   * @type {string}
   * @memberof AnswerDto
   */
  idQuiz?: string
}

/**
 * Check if a given object implements the AnswerDto interface.
 */
export function instanceOfAnswerDto(value: object): value is AnswerDto {
  if (!('text' in value) || value['text'] === undefined) return false
  if (!('isCorrect' in value) || value['isCorrect'] === undefined) return false
  return true
}

export function AnswerDtoFromJSON(json: any): AnswerDto {
  return AnswerDtoFromJSONTyped(json, false)
}

export function AnswerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerDto {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    text: json['text'],
    isCorrect: json['isCorrect'],
    idQuestion: json['idQuestion'] == null ? undefined : json['idQuestion'],
    idQuiz: json['idQuiz'] == null ? undefined : json['idQuiz']
  }
}

export function AnswerDtoToJSON(value?: AnswerDto | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    text: value['text'],
    isCorrect: value['isCorrect'],
    idQuestion: value['idQuestion'],
    idQuiz: value['idQuiz']
  }
}
