/* tslint:disable */
/* eslint-disable */
/**
 * Tech Web - OpenAPI 3.0
 * Prova
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime'
/**
 *
 * @export
 * @interface Problem
 */
export interface Problem {
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  title?: string
  /**
   *
   * @type {number}
   * @memberof Problem
   */
  status?: number
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  detail?: string
  /**
   *
   * @type {string}
   * @memberof Problem
   */
  instance?: string
}

/**
 * Check if a given object implements the Problem interface.
 */
export function instanceOfProblem(value: object): value is Problem {
  return true
}

export function ProblemFromJSON(json: any): Problem {
  return ProblemFromJSONTyped(json, false)
}

export function ProblemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Problem {
  if (json == null) {
    return json
  }
  return {
    type: json['type'] == null ? undefined : json['type'],
    title: json['title'] == null ? undefined : json['title'],
    status: json['status'] == null ? undefined : json['status'],
    detail: json['detail'] == null ? undefined : json['detail'],
    instance: json['instance'] == null ? undefined : json['instance']
  }
}

export function ProblemToJSON(value?: Problem | null): any {
  if (value == null) {
    return value
  }
  return {
    type: value['type'],
    title: value['title'],
    status: value['status'],
    detail: value['detail'],
    instance: value['instance']
  }
}
