/* tslint:disable */
/* eslint-disable */
/**
 * Tech Web - OpenAPI 3.0
 * Prova
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime'
import type { AnswerDto } from './AnswerDto'
import { AnswerDtoFromJSON, AnswerDtoFromJSONTyped, AnswerDtoToJSON } from './AnswerDto'

/**
 *
 * @export
 * @interface QuestionDto
 */
export interface QuestionDto {
  /**
   *
   * @type {string}
   * @memberof QuestionDto
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof QuestionDto
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof QuestionDto
   */
  idQuiz?: string
  /**
   *
   * @type {Array<AnswerDto>}
   * @memberof QuestionDto
   */
  answers: Array<AnswerDto>
}

/**
 * Check if a given object implements the QuestionDto interface.
 */
export function instanceOfQuestionDto(value: object): value is QuestionDto {
  if (!('title' in value) || value['title'] === undefined) return false
  if (!('answers' in value) || value['answers'] === undefined) return false
  return true
}

export function QuestionDtoFromJSON(json: any): QuestionDto {
  return QuestionDtoFromJSONTyped(json, false)
}

export function QuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionDto {
  if (json == null) {
    return json
  }
  return {
    title: json['title'],
    id: json['id'] == null ? undefined : json['id'],
    idQuiz: json['idQuiz'] == null ? undefined : json['idQuiz'],
    answers: (json['answers'] as Array<any>).map(AnswerDtoFromJSON)
  }
}

export function QuestionDtoToJSON(value?: QuestionDto | null): any {
  if (value == null) {
    return value
  }
  return {
    title: value['title'],
    id: value['id'],
    idQuiz: value['idQuiz'],
    answers: (value['answers'] as Array<any>).map(AnswerDtoToJSON)
  }
}
