/* tslint:disable */
/* eslint-disable */
/**
 * Tech Web - OpenAPI 3.0
 * Prova
 *
 * The version of the OpenAPI document: 1.0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from './runtime'
/**
 *
 * @export
 * @interface QuestionResponseDto
 */
export interface QuestionResponseDto {
  /**
   *
   * @type {string}
   * @memberof QuestionResponseDto
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof QuestionResponseDto
   */
  answer?: string
}

/**
 * Check if a given object implements the QuestionResponseDto interface.
 */
export function instanceOfQuestionResponseDto(value: object): value is QuestionResponseDto {
  return true
}

export function QuestionResponseDtoFromJSON(json: any): QuestionResponseDto {
  return QuestionResponseDtoFromJSONTyped(json, false)
}

export function QuestionResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): QuestionResponseDto {
  if (json == null) {
    return json
  }
  return {
    id: json['id'] == null ? undefined : json['id'],
    answer: json['answer'] == null ? undefined : json['answer']
  }
}

export function QuestionResponseDtoToJSON(value?: QuestionResponseDto | null): any {
  if (value == null) {
    return value
  }
  return {
    id: value['id'],
    answer: value['answer']
  }
}
